### ISSUE TITLE
Solr zookeeper loaded up with >100k status entries in `/overseer/collection-queue-work`

### ISSUE THREAD

**Issue by datadavev** [DataONEorg/dataone-solr#1]
The solr console log at `/var/solr/server/logs/solr-8983-console.log` was growing rapidly with entries like:
```
20240206-20:49:17: [ERROR]: :org.apache.zookeeper.KeeperException$NoNodeException: KeeperErrorCode = NoNode for /overseer/collection-queue-work/qn-0000591708
	at org.apache.zookeeper.KeeperException.create(KeeperException.java:111)
	at org.apache.zookeeper.KeeperException.create(KeeperException.java:51)
	at org.apache.zookeeper.ZooKeeper.getData(ZooKeeper.java:1155)
	at org.apache.solr.common.cloud.SolrZkClient$7.execute(SolrZkClient.java:345)
	at org.apache.solr.common.cloud.SolrZkClient$7.execute(SolrZkClient.java:342)
	at org.apache.solr.common.cloud.ZkCmdExecutor.retryOperation(ZkCmdExecutor.java:61)
	at org.apache.solr.common.cloud.SolrZkClient.getData(SolrZkClient.java:342)
	at org.apache.solr.cloud.DistributedQueue.remove(DistributedQueue.java:229)
	at org.apache.solr.cloud.OverseerCollectionProcessor.cleanUpWorkQueue(OverseerCollectionProcessor.java:389)
	at org.apache.solr.cloud.OverseerCollectionProcessor.run(OverseerCollectionProcessor.java:285)
	at java.lang.Thread.run(Thread.java:750)
 [org.apache.solr.cloud.OverseerCollectionProcessor]
```

Examining zookeeper reveals over 137000 entries reporting like:

```
   /overseer/collection-queue-work/qn-0000666346 (0)
   DATA:
       {"operation":"clusterstatus"}
```

when examining the zookeeper database like:
```
/var/solr/server/scripts/cloud-scripts/zkcli.sh -zkhost localhost:2181 -cmd list /overseer/collection-queue-work
```

The large number of entries seems to lead to a slowdown of zookeeper which in turn causes a cluster status request to timeout. This seems to be a known issue with solr < 8, and it is not clear why this error shows up sometimes.

Reported solutions are to delete the entire overseer collection and restart the entire solr cluster. This seems overly invasive and requires a complete shutdown of all solr nodes to facilitate the recovery.

Solution implemented is to use a small python script to delete the status entries one at a time, then restart solr. This process is slow (a couple hours) when the number of status entries is large. The python script is:

```python
# fix_solr_status.py
import kazoo.client


def main():
    host = "127.0.0.1:2181"
    root = "/overseer/collection-queue-work/"
    zk = kazoo.client.KazooClient(hosts=host)
    zk.start()
    try:
        for key in zk.get_children(root):
            if key.startswith("qn-"):
                _path = f"{root}{key}"
                print(f"deleting {_path}")
                zk.delete(_path)
    finally:
        zk.stop()


if __name__ == "__main__":
    main()
```

It can be run on one of the CN nodes while solr is operational.

**Comment by datadavev** [comment]
Another symptom of the problem is the failure of a CLUSTERSTATUS request, e.g.:
```
curl "http://localhost:8983/solr/admin/collections?action=CLUSTERSTATUS&wt=json"

{
  "responseHeader": {
    "status": 500,
    "QTime": 180205
  },
  "error": {
    "msg": "clusterstatus the collection time out:180s",
    "trace": "org.apache.solr.common.SolrException: clusterstatus the collection time out:180s\n\tat org.apache.solr.handler.admin.CollectionsHandler.handleResponse(CollectionsHandler.java:237)\n\tat org.apache.solr.handler.admin.CollectionsHandler.handleRequestBody(CollectionsHandler.java:168)\n\tat org.apache.solr.handler.RequestHandlerBase.handleRequest(RequestHandlerBase.java:143)\n\tat org.apache.solr.servlet.HttpSolrCall.handleAdminRequest(HttpSolrCall.java:660)\n\tat org.apache.solr.servlet.HttpSolrCall.call(HttpSolrCall.java:431)\n\tat org.apache.solr.servlet.SolrDispatchFilter.doFilter(SolrDispatchFilter.java:227)\n\tat org.apache.solr.servlet.SolrDispatchFilter.doFilter(SolrDispatchFilter.java:196)\n\tat org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)\n\tat org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585)\n\tat org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)\n\tat org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:577)\n\tat org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223)\n\tat org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)\n\tat org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)\n\tat org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)\n\tat org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)\n\tat org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)\n\tat org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:215)\n\tat org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:110)\n\tat org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)\n\tat org.eclipse.jetty.server.Server.handle(Server.java:497)\n\tat org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:310)\n\tat org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)\n\tat org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)\n\tat org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)\n\tat org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)\n\tat java.lang.Thread.run(Thread.java:750)\n",
    "code": 500
  }
}
```

**Comment by datadavev** [comment]
Once the python script is complete, it is necessary to restart solr and zookeeper on all nodes, however it is not necessary for all nodes to be shutdown at the same time.

**Comment by datadavev** [comment]
To count the number of `clusterstatus` entries in ZK:
```
/var/solr/server/scripts/cloud-scripts/zkcli.sh -zkhost localhost:2181 -cmd list /overseer/collection-queue-work | grep "clusterstatus" | wc -l
```

**Comment by taojing2002** [comment]
Here are the steps to fix the issue:

1. Put the CNs into read-only mode
2. Restart Zookeeper/Solr on all nodes ( it is not necessary for all nodes to be shutdown at the same time)
3. Run the Python script to remove unnecessary requests from zookeeper
4. Restart Zookeeper/Solr on all nodes again
5. Check the cluster status (see below)
6. Leave read-only mode

Note: restarting Solr will automatically remove the huge solr console file.

Checking cluster status. The quick check is that both nodes are listed in the `live_nodes` key at the end:
```
curl "http://localhost:8983/solr/admin/collections?action=CLUSTERSTATUS&wt=json&indent=on"
{
  "responseHeader":{
    "status":0,
    "QTime":859},
  "cluster":{
    "collections":{
      "event_core":{
        "shards":{"shard1":{
            "range":"80000000-7fffffff",
            "state":"active",
            "replicas":{
              "core_node2":{
                "core":"event_core_shard1_replica1",
                "base_url":"http://207.71.230.213:8983/solr",
                "node_name":"207.71.230.213:8983_solr",
                "state":"active"},
              "core_node3":{
                "core":"event_core_shard1_replica3",
                "base_url":"http://128.111.85.180:8983/solr",
                "node_name":"128.111.85.180:8983_solr",
                "state":"active",
                "leader":"true"}}}},
        "replicationFactor":"2",
        "router":{"name":"compositeId"},
        "maxShardsPerNode":"1",
        "autoAddReplicas":"false",
        "configName":"event_core"},
      "search_core":{
        "shards":{"shard1":{
            "range":"80000000-7fffffff",
            "state":"active",
            "replicas":{
              "core_node2":{
                "core":"search_core_shard1_replica2",
                "base_url":"http://207.71.230.213:8983/solr",
                "node_name":"207.71.230.213:8983_solr",
                "state":"active"},
              "core_node3":{
                "core":"search_core_shard1_replica1",
                "base_url":"http://128.111.85.180:8983/solr",
                "node_name":"128.111.85.180:8983_solr",
                "state":"active",
                "leader":"true"}}}},
        "replicationFactor":"2",
        "router":{"name":"compositeId"},
        "maxShardsPerNode":"1",
        "autoAddReplicas":"false",
        "configName":"search_core"}},
    "live_nodes":["128.111.85.180:8983_solr",
      "207.71.230.213:8983_solr"]}}
```
